# Generated by Django 3.1.1 on 2020-09-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=50)),
                ('bookPrice', models.CharField(max_length=5)),
                ('bookPages', models.IntegerField()),
                ('bookPublisher', models.CharField(max_length=30)),
            ],
        ),
    ]
