# Generated by Django 3.1.1 on 2020-09-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('isComplete', models.BooleanField(default=False)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
