# Generated by Django 2.2.7 on 2020-09-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollQuestion', models.CharField(max_length=100)),
                ('option_1', models.CharField(default='', max_length=15)),
                ('option_2', models.CharField(default='', max_length=15)),
                ('option_3', models.CharField(default='', max_length=15)),
                ('option_4', models.CharField(default='', max_length=15)),
                ('option1_count', models.IntegerField(default=0)),
                ('option2_count', models.IntegerField(default=0)),
                ('option3_count', models.IntegerField(default=0)),
                ('option4_count', models.IntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
